/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Conceptos.Cliente;
import Conceptos.Estado;
import Conceptos.Mecanico;
import Conceptos.Servicio;
import Conceptos.Solicitud;
import Util.GestorDatos;
import Util.GuardarArchivo;
import Util.cargadorXML;
import javax.swing.*;
import java.awt.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;

/**
 *
 * @author Matias
 */
public class Menu extends javax.swing.JFrame {

    private final GestorDatos gestorDatos = GestorDatos.getInstancia();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // Detectar cambios de estado
        addWindowStateListener((java.awt.event.WindowEvent e) -> {
            if ((e.getNewState() & javax.swing.JFrame.MAXIMIZED_BOTH) == javax.swing.JFrame.MAXIMIZED_BOTH) {
                System.out.println("Ventana maximizada");
            } else if (e.getNewState() == javax.swing.JFrame.NORMAL) {
                // tamaño al restaurar
                setSize(1024, 768);
                setLocationRelativeTo(null);
            }
        });

        //Imagen de Clientes
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/imagenes/clientes.png"));
        Image img1 = icon1.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jButton1.setIcon(new ImageIcon(img1));

        //Imagen de Mecánicos
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/imagenes/mecanicos.png"));
        Image img2 = icon2.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jButton2.setIcon(new ImageIcon(img2));

        // Imagen de Servicios
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/imagenes/servicios.png"));
        Image img3 = icon3.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jButton3.setIcon(new ImageIcon(img3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Importar = new javax.swing.JButton();
        Exportar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taller Mecanico");
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 50, 20));

        jLabel3.setText("Servicios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 50, 20));

        jLabel2.setText("Mecanicos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 70, 20));

        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 170, 140));

        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 180, 140));

        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 180, 140));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 307, 830, -1));

        jLabel4.setText("Consutar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, 20));

        jLabel5.setText("Solicitar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 60, 20));

        jLabel6.setText("Atender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, 150));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 170, 150));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 170, 150));

        Importar.setText("Importar");
        Importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarActionPerformed(evt);
            }
        });
        getContentPane().add(Importar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        Exportar.setText("Exportar");
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });
        getContentPane().add(Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        setVisible(false);
        try {
            ventanaServicios servicios = new ventanaServicios(Menu.this, true);
            servicios.setVisible(true);
        } finally {
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        setVisible(false);
        try {
            ventanaMecanico mecanicos = new ventanaMecanico(Menu.this, true);
            mecanicos.setVisible(true);
        } finally {
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        setVisible(false);
        try {
            ventanaClientes clientes = new ventanaClientes(Menu.this, true);
            clientes.setVisible(true);
        } finally {
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        setVisible(false);
        try {
            ventanaConsultar consultar = new ventanaConsultar(Menu.this, true);
            consultar.setVisible(true);
        } finally {
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        setVisible(false);
        try {
            ventanaSolicitar solicitar = new ventanaSolicitar(Menu.this, true);
            solicitar.setVisible(true);
        } finally {
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        setVisible(false);
        try {
            ventanaAtender atender = new ventanaAtender(Menu.this, true);
            atender.setVisible(true);
        } finally {
            setVisible(true);
            setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarActionPerformed
        try {
            ArrayList<Cliente> clientes = cargarXML("src/Export/clientes.xml", "cliente");
            ArrayList<Mecanico> mecanicos = cargarXML("src/Export/mecanicos.xml", "mecanico");
            ArrayList<Servicio> servicios = cargarXML("src/Export/servicios.xml", "servicio");
            ArrayList<Estado> estados = cargarXML("src/Export/estados.xml", "estado");
            ArrayList<Solicitud> solicitudes = cargarXML("src/Export/solicitudes.xml", "solicitud");

            gestorDatos.importarDatos(clientes, servicios, mecanicos, solicitudes, estados);
            mostrarMensaje("Datos importados y guardados en .DAT", JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            mostrarMensaje("No se encontraron los archivos XML de exportación", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            mostrarMensaje("Ocurrió un error al importar: " + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ImportarActionPerformed

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
        try {
            GuardarArchivo.guardarClientes(gestorDatos.getClientes());
            GuardarArchivo.guardarMecanicos(gestorDatos.getMecanicos());
            GuardarArchivo.guardarServicios(gestorDatos.getServicios());
            GuardarArchivo.guardarEstados(gestorDatos.getEstados());
            GuardarArchivo.guardarSolicitudes(gestorDatos.getSolicitudes());
            mostrarMensaje("Datos exportados a XML", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            mostrarMensaje("No fue posible exportar los datos: " + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ExportarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        gestorDatos.limpiarDatos();
        mostrarMensaje("Datos borrados y archivos .DAT vacíos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LimpiarActionPerformed

    private <T> ArrayList<T> cargarXML(String ruta, String tipo) throws FileNotFoundException {
        try (FileInputStream fis = new FileInputStream(ruta)) {
            return (ArrayList<T>) cargadorXML.Cargar(fis, tipo);
        }
    }

    private void mostrarMensaje(String mensaje, int tipo) {
        JOptionPane.showMessageDialog(this, mensaje, "Taller Mecánico", tipo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exportar;
    private javax.swing.JButton Importar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
